R/add_comparison.R, R/data.R, R/tbl_summary.R, R/tbl_survival.R, R/utils-tbl_summary.R, inst/WORDLIST, man/add_comparison.Rd, man/assign_stat_display.Rd, man/tbl_summary.Rd, man/tbl_survival.Rd, man/trial.Rd, tests/testthat/test-tbl_summary_input_checks.R
#50 updates to `tbl_summary` inputs
=> Summary arg inpus

R/tbl_merge.R, R/tbl_regression.R, R/tbl_uvregression.R, R/utils-tbl_regression.R
Fixes for issue #81 
@michaelcurry1123 I think this should resolve the issue.
There could still be sorting issues when merging on categorical variables that do not match. But, I think this is good enough for now.  Would you mind doing a review before we merge?
=> #81 tbl merge ref group

R/add_comparison.R, R/add_global.R, R/add_q.R, R/inline_text.R, R/tab_style_bold_p.R, R/tbl_merge.R, R/tbl_regression.R, R/tbl_survival.R, R/tbl_uvregression.R, R/utils-tbl_regression.R, man/inline_text.tbl_regression.Rd, man/inline_text.tbl_summary.Rd, man/inline_text.tbl_survival.Rd, man/inline_text.tbl_uvregression.Rd, man/tbl_regression.Rd, man/tbl_uvregression.Rd, tests/testthat/test-add_q.R, tests/testthat/test-inline_text.R, vignettes/tbl_regression.Rmd
=> #97 naming conventions

R/tbl_summary.R, R/utils-tbl_summary.R
=> #106 ignore unsupported types

DESCRIPTION, NEWS.md, R/tbl_stack.R
=> fixed tbl_uvregression error in tbl_stack

R/gtsummary-package.R, R/tbl_merge.R, R/utils-tbl_summary.R
I'm working on revdep checks as we work towards the release of tidyr v1.0.0. We see this for gtsummary:
https://github.com/tidyverse/tidyr/blob/master/revdep/problems.md#gtsummary
This PR will work with the current version of tidyr (v0.8.3), but also with the changes coming in what's slated to become v1.0.0. After the tidyr release dust has settled, you might eventually want to bump the minimum version and take this conditional code back out.
=> Prepare for tidyr v1.0.0

DESCRIPTION, codemeta.json, vignettes/tbl_regression.Rmd, vignettes/tbl_summary.Rmd
Added the code below to the vignettes to download and install gt before the vignette runs.
```r
if (curl::has_internet()) {
temp_path <- file.path(tempdir(), "gt_folder")
dir.create(temp_path)
lib_path <-.libPaths()
.libPaths(c(lib_path, temp_path))
remotes::install_github("rstudio/gt", lib = temp_path)
}
```
#267 
=> 267 install from gh

NEWS.md, README.Rmd, README.md, pkgdown/_pkgdown.yml, vignettes/global_options.Rmd
Added vignette explaining global options that can be set
#289 
=> 289 options vignette

vignettes/global_options.Rmd
Small vignette language change.
=> small changes to Global Options vignette

.Rbuildignore, .covrignore, DESCRIPTION, NEWS.md, R/tbl_stack.R, R/tbl_uvregression.R, codemeta.json, tests/testthat/test-add_n.R, tests/testthat/test-tbl_stack.R, tests/testthat/test-tbl_uvregression.R
NSE Bug fix when bare (NSE) arguments are passed in `method.args=` in `tbl_uvregression()`.  The update to the code resulted in a refactoring of how the regression models are built.  Now, the `method=` and all arguments are coalesced into a proper function call, which is then evaluated.  A SO response was helpful for making this update https://stackoverflow.com/questions/59433187/r-convert-elements-of-list-into-expression-from-function-input
#322 
These are the 3 types of calls used for primary testing.
```r
tbl_uvregression(
trial %>% dplyr::select(response, age, grade),
method = glm,
y = response,
method.args = list(family = binomial),
exponentiate = …
```
=> #322 fixed NSE bug in method.args

DESCRIPTION, NEWS.md, R/tbl_summary.R, R/utils-tbl_summary.R, codemeta.json, tests/testthat/test-tbl_summary.R, tests/testthat/test-tbl_summary_input_checks.R
`tbl_summary()` will now summarize `datediff` class columns
#343 
=> 343 difftime class

R/tidyselect_to_list.R, vignettes/tbl_summary.Rmd
I made updates to the tidyselect portion of the tbl_summary vignette.  Not entirely satisfied with it, but I think better than it was.
=> Updated selector section of tbl_summary vignette

DESCRIPTION, NEWS.md, R/add_n.R, R/add_nevent.R, R/add_overall.R, R/add_p.R, R/combine_terms.R, R/modify_header.R, R/tbl_merge.R, R/tbl_regression.R, R/tbl_stack.R, R/tidyselect_to_list.R, R/utils-tbl_regression.R, R/utils-tbl_summary.R, codemeta.json
Updated most `class()==` or `class() %in%` to `inherits()`
=> updated class() to inherits()

DESCRIPTION, NEWS.md, R/tidy_vetted.R, R/utils-tbl_regression.R, codemeta.json, data-raw/gt_sha.R, man/tidy_vetted.Rd, tests/testthat/test-tbl_regression.R
=> added broom.mix tidy back to package

.travis.yml, R/tbl_summary.R, R/utils-tbl_summary.R
I moved the checks on the data argument in tbl_summary higher up
#392 
=> moved data input check for tbl_summary

R/inline_text.R, R/tbl_survfit.R, man/inline_text.tbl_survfit.Rd, tests/testthat/test-inline_text.R
=> inline text updates for survfit

.github/workflows/R-CMD-check.yaml, .github/workflows/pkgdown.yaml, .github/workflows/pr-commands.yaml, .github/workflows/test-coverage.yaml
Updating GH Actions
closes #475
=> gh actions update

.github/workflows/R-CMD-check.yaml, .github/workflows/pkgdown.yaml, .github/workflows/test-coverage.yaml
=> gh updates

.github/workflows/pkgdown.yaml, DESCRIPTION, LICENSE.md, R/add_global_p.R, R/style_number.R, R/style_percent.R, R/style_pvalue.R, R/style_ratio.R, R/style_sigfig.R, R/zzz.R, man/style_number.Rd, man/style_percent.Rd, man/style_pvalue.Rd, man/style_ratio.Rd, man/style_sigfig.Rd, man/theme_gtsummary.Rd
- Updated license
- Updated the `style_*()` family to only search for theme defaults once in `style_number()` as all other functions use this under the hood.
- Added messages to print when package is loaded
- Improved messaging when `add_global_p()` is run
=> Misc updates

NEWS.md, inst/WORDLIST, tests/testthat/test-style_sigfig.R
Added a unit test and a line to NEWS.md related to this bug fix.
=> adding test-style_sigfig and a line about bug fix #638 to NEWS.md

.github/pull_request_template.md, DESCRIPTION, NEWS.md, R/style_percent.R, man/style_percent.Rd, tests/testthat/test-style_percent.R
Added a digits argument to `style_percent()`
closes #690
=> added digits= arg to style_percent

R/add_overall.R
- Messaging fix for the merge in `add_overall()`. This messaging bug was introduced when we switched to broom.helpers. THIS DOES NOT NEED TO GO INTO NEWS.md
closes #706
=> Merge fix for add_overall

R/add_global_p.R, R/tbl_uvregression.R, tests/testthat/test-add_global_p.R
- Updates have been made to `tbl_uvregression()` and `add_global_p.tbl_uvregression()` to handle variables with non-standard names, e.g. variables names with spaces (#686)
closes #686 
cc @gorkang @larmarange 
=> `tbl_uvregression()` fix for variables it non-standard names

.github/workflows/R-CMD-check.yaml, DESCRIPTION
=> Re-adding GH Actions checks for old R Versions

vignettes/tbl_summary.Rmd
* Add table showing different ways to use statistic argument 
* Include slide if in_pkgdown
=> tbl_summary update vignette

DESCRIPTION, R/add_p.R
Now passing the formal gtsummary object to the testing function that is used in some tests (e.g. `prop.test()`)
=> `add_p.tbl_summary` passed gtsummary object to p-value calculation fn

.github/workflows/R-CMD-check.yaml, DESCRIPTION, NEWS.md, R/modify.R, R/select_helpers.R, man/select_helpers.Rd, tests/testthat/test-custom_tidiers.R, tests/testthat/test-select_helpers.R
- restored previous functionality of `all_continuous()`
- added unit test for nnet::multinom() models
=> Misc updates before release

.github/workflows/continuous-benchmarks.yaml, bench/bench-tbl_summary.R
=> Add benchmarking

R/tbl_merge.R
Improved messaging when a `tbl_merge()` will likely fail.
closes #769 
**No need to update NEWS or the version number for this PR.**
=> Update tbl_merge messaging

.github/workflows/continuous-benchmarks.yaml, .github/workflows/test-coverage.yaml
=> Caching pkgs in continuous benchmark

DESCRIPTION, NEWS.md, R/custom_tidiers.R, tests/testthat/test-custom_tidiers.R
=> added exp arg to gam tidier

DESCRIPTION, R/add_p.R, R/modify.R, R/modify_fmt_fun.R, R/modify_table_styling.R, R/tbl_merge.R, R/tbl_stack.R, R/utils-as.R, R/utils-gtsummary_core.R, R/utils-tbl_regression.R, inst/WORDLIST, man/gtsummary-package.Rd, man/modify.Rd, man/modify_fmt_fun.Rd, man/modify_table_styling.Rd, tests/testthat/test-as_flex_table.R, tests/testthat/test-as_gt.R, tests/testthat/test-as_hux_table.R, tests/testthat/test-as_kable_extra.R, tests/testthat/test-modify_footnote.R, tests/testthat/test-modify_table_styling.R
Updated the `rows=` argument in all functions to be a quosure, to better manage environments
closes #784
-------------------------------------------------------------------------------
=> Updates `rows=` argument to quosure

DESCRIPTION, NEWS.md, R/tbl_summary.R, R/tbl_survfit.R, R/tbl_uvregression.R, R/utils-tbl_summary.R
* Added a message to users if they pass columns with class `"haven_labelled"` to either `tbl_summary()` or `tbl_svysummary()` (#805)
closes #805 
=> haven_labelled messaging for tbl_summary/tbl_svysummary

DESCRIPTION, NEWS.md, R/tbl_uvregression.R, tests/testthat/test-tbl_uvregression.R
* Improved error messaging when there is a problem constructing one of the univariate regression models in `tbl_uvregression()`
=> Improve error messaging in `tbl_uvregression()`

DESCRIPTION, NEWS.md, R/as_gt.R
*Adding messaging for gt caption requests when the version of gt does not support captions
=> messaging for gt captions

README.Rmd, README.md
=> readme udpates

DESCRIPTION, R/utils-as.R
=> fix merge bug with text formatting

DESCRIPTION, R/utils-gtsummary_core.R
=> Update table styling

R/theme_gtsummary.R
=> Jama update

DESCRIPTION, R/utils-as.R
=> Text format fix

DESCRIPTION, NEWS.md, R/add_significance_stars.R, R/add_stat_label.R, R/as_flex_table.R, R/as_hux_table.R, R/as_kable.R, R/as_kable_extra.R, R/as_tibble.R, R/modify_table_styling.R, R/theme_gtsummary.R, R/utils-as.R, man/modify_table_styling.Rd, tests/testthat/test-add_significance_stars.R, tests/testthat/test-as_gt.R, tests/testthat/test-modify_table_styling.R
=> Column merging is now user-facing

DESCRIPTION, NEWS.md, R/add_difference.R, R/add_glance.R, R/add_p.R, R/add_stat.R, R/inline_text.R, R/modify_column_hide.R, R/modify_fmt_fun.R, R/modify_table_body.R, R/modify_table_styling.R, R/tbl_cross.R, R/tbl_regression.R, R/tbl_svysummary.R, man/add_difference.Rd, man/add_glance.Rd, man/add_p.tbl_svysummary.Rd, man/add_stat.Rd, man/inline_text.Rd, man/modify_column_hide.Rd, man/modify_fmt_fun.Rd, man/modify_table_body.Rd, man/modify_table_styling.Rd, man/tbl_cross.Rd, man/tbl_regression.Rd, man/tbl_regression_methods.Rd, man/tbl_svysummary.Rd, man/tbl_uvregression.Rd
- In the default `tidy_fun = broom::tidy` fails, `parameters::model_parameters()` attempts to tidy the model, if {parameters} is installed. (#854)
closes #854
closes #858 
=> Documentation updates + using `broom::tidy` + `parameters::model_parameters()`

NEWS.md, R/add_glance.R, R/tbl_uvregression.R, man/add_glance.Rd, tests/testthat/test-add_glance.R, tests/testthat/test-add_p.tbl_summary.R, tests/testthat/test-tbl_summary.R, tests/testthat/test-tbl_uvregression.R
=> update default fmt_fun for some glance stats

DESCRIPTION, NEWS.md, R/tbl_svysummary.R
=> compatibility of tbl_svysummary() with srvyr

DESCRIPTION, NEWS.md, R/inline_text.R, codemeta.json, inst/WORDLIST, tests/spelling.R, tests/testthat/test-inline_text.R
* Messaging update when `inline_text.gtsummary()` suspects a variable has been repeated in the gtsummary table. (#855)
closes #855
``` r
#> #BlackLivesMatter
packageVersion("gtsummary")
#> [1] '1.4.0.9002'
t1 <- lm(age ~ marker, trial) %>% tbl_regression()
tbl_stack(list(t1, t1)) %>%
inline_text(variable = marker, column = estimate)
#> Variable 'marker' likely not unique in gtsummary table, the cell you wish
#> to display may not be accessible. This may occurs when gtsummary tables with
#> repeated variable names are combined using `tbl_stack()`.
#> [1] "-0.05"
```
<sup>Created on 2021-04-30 by the [reprex …
=> msg update for repeated variables in `inline_text()`

DESCRIPTION, NEWS.md, R/as_flex_table.R, R/as_gt.R, R/as_hux_table.R, R/as_kable_extra.R, R/modify_table_styling.R, R/utils-as.R, man/modify_table_styling.Rd, tests/testthat/test-as_flex_table.R, tests/testthat/test-as_gt.R, tests/testthat/test-as_hux_table.R, tests/testthat/test-as_kable_extra.R
=> adding a double indent option

DESCRIPTION, NEWS.md, R/style_pvalue.R, gtsummary/renv/.gitignore
* Update `style_pvalue()` to format p-values slightly larger than 1 and slightly lower than 0 (due to imprecise numeric storage on machines). (#907)
closes #907 
=> `style_pvalue()` update for p-values near 1 and 0

DESCRIPTION, NEWS.md, R/add_p.R, renv.lock, tests/testthat/test-add_p.tbl_cross.R
=> `add_p.tbl_cross(pvalue_fun=)` bug fix

R/as_tibble.R, renv.lock, tests/testthat/test-as_tibble.R
* Fix allowing for factor vectors to be passed in `tlb_stack(group_header=)`. (#908)
closes #908
=> #908 group_header fix for factors in tbl_stack()

DESCRIPTION, NEWS.md, R/tbl_uvregression.R, codemeta.json, tests/testthat/test-tbl_uvregression.R
* Updated arguments `y=` and `x=` in `tbl_uvregression()` to allow for non-standard names (#912)
closes #912 
=> #912 fix for odd names in y and x arguments

DESCRIPTION, NEWS.md, R/tbl_svysummary.R, renv.lock
* Variables passed in the `tbl_svysummary(by=)` argument will now automatically be added to `include=`.  (#925)
closes #925
=> `tbl_svysummary(by=)` argument will now automatically be added to `include=`

DESCRIPTION, NEWS.md, R/tbl_stack.R, R/tbl_svysummary.R, man/add_global_p.Rd, man/add_n.tbl_summary.Rd, man/add_n.tbl_survfit.Rd, man/add_nevent.tbl_survfit.Rd, man/add_overall.Rd, man/add_p.tbl_summary.Rd, man/add_p.tbl_survfit.Rd, man/add_p.tbl_svysummary.Rd, man/add_q.Rd, man/add_stat_label.Rd, man/bold_italicize_labels_levels.Rd, man/combine_terms.Rd, man/inline_text.tbl_regression.Rd, man/inline_text.tbl_summary.Rd, man/inline_text.tbl_survfit.Rd, man/inline_text.tbl_uvregression.Rd, man/tbl_merge.Rd, man/tbl_regression.Rd, man/tbl_stack.Rd, man/tbl_summary.Rd, man/tbl_survfit.Rd, man/tbl_svysummary.Rd, man/tbl_uvregression.Rd, renv.lock, tests/testthat/test-tbl_stack.R
* Update to the internals of `tbl_stack()` to better handle when two or more stacked tables are then stacked again and again and again.  (#906)
Previously, when tables were stacked with `tbl_stack()` the column `"tbl_id"` was added to the `x$table_body` as an ID to identify which rows came from which tables. There was a potential issue when tables are stack with `tbl_stack()`, and then again stacked with `tbl_stack()` since the column `"tbl_id"` was being overwritten by the most recent `tbl_stack()` call.  The update changes the column name to `tbl_id1`, and if it is stacked again, then it's called `tbl_id2`, and so on.
This is important because the table ID appears in the `rows` formatting expression found in `x$table_styling`.
**If …
=> `tbl_id` column name update in tbl_stack()

DESCRIPTION, NEWS.md, R/add_difference.R
=> bug fix for estimate_fun arg

R/add_stat.R, man/add_stat.Rd
=> documentation updates for deprecated arguments in `add_stat()`

.github/workflows/R-CMD-check.yaml, DESCRIPTION, NEWS.md, R/utils-add_p_tests.R, codemeta.json
* Now using `broom::tidy()` to prepare `aov()` test results in `add_p.tbl_summary()`, which adds additional columns to `.$table_body()`. (#956) 
closes #956
=> Returning `broom::tidy()` columns in `aov()` test

DESCRIPTION, NEWS.md, R/utils-add_p.R, R/utils-tbl_summary.R, tests/testthat/test-add_p.tbl_summary.R, tests/testthat/test-tbl_summary.R
* Fix in `tbl_summary()` when a factor variable is passed that is all NA with no specified levels.
* Fix in `add_p.tbl_summary()` when a factor variable with all NA values is passed. 
closes #977
=> Fixes in `tbl_summary()` and `add_p.tbl_summary()` when fct with all NA passed

.Rprofile, DESCRIPTION, man/gtsummary-package.Rd, renv.lock
Depending on dev version of broom.helpers
=> dep on broom.helpers dev version

NEWS.md, R/utils-add_p.R
* Fix in `add_p()`/`add_difference()` when check whether the passed test is an internal method or a custom method. The previous code required Suggested packages, such as, {lme4}, {effectsize}, and {survey}, to be installed. (#1018)
closes #1018
=> `add_difference()` fix for uninstalled suggested pacakges

DESCRIPTION, NEWS.md, R/tbl_continuous.R, tests/testthat/test-tbl_continuous.R
- Fix in `tbl_continuous()` when `include=` is not specified.
- Added class `"tbl_continuous"` to the output of `tbl_continuous()`.
=> Fix in `tbl_continuous()` when `include=` is not specified.

DESCRIPTION, NEWS.md, R/tbl_regression_methods.R, tests/testthat/test-custom_tidiers.R
* Fix in `as_tibble()` for `nnet::multinom()` regression models.
=> Multinom fix for `as_tibble()`

NEWS.md, R/add_stat.R, man/add_stat.Rd, tests/testthat/test-add_stat.R
=> `add_stat()` to accept `tbl_continuous()` tables

DESCRIPTION, NEWS.md, R/add_n.R
- The N column added with `add_n.tbl_regression()` will now be styled with `style_number()`. (#1022)
closes #1022
=> Adding a formatting function to `add_n.tbl_regression()`

pkgdown/_pkgdown.yml
=> Added `tbl_custom_summary()` to _pkgdown.yml

DESCRIPTION, NEWS.md, R/utils-tbl_summary.R, tests/testthat/test-tbl_custom_summary.R
* Updated the default formatting functions in `tbl_custom_summary()`. Previously, summaries with character results errored because the default summary function was `style_number()`. This has been updated to `style_sigfig()` for numeric columns, and `as.character()` for everything else. (#983)
closes #983
=> Default formatting functions in `adding_formatting_as_attr()` update

DESCRIPTION, NEWS.md, R/add_overall.R, man/add_overall.Rd, man/gtsummary-package.Rd
- Updating the `add_overall()` S3 method to have a more common structure, e.g. `add_overall(x, ....)`, where previously, the `...` were not present. (#1066)
closes #1066
=> Added dots to `add_overall()` S3 method

DESCRIPTION, NEWS.md, R/tbl_regression_methods.R
* Multinomial models computed using MICE are now supported. (#1065)
closes #1065
=> MICE + Multinomial Models

DESCRIPTION, NEWS.md, R/inline_text.R, tests/testthat/test-inline_text.R
=> #1078 fix for inline_text.gtsummary()

NEWS.md, R/syntax.R, man/syntax.Rd
=> doc updates

NEWS.md, R/tbl_strata.R, codemeta.json, man/gtsummary-package.Rd, man/tbl_strata.Rd, tests/testthat/test-tbl_strata.R
* The `tbl_strata(.combine_args=)` has been added that lets you control all arguments in the `tbl_merge()` or `tbl_stack()` that occurs in `tbl_strata()` (#1090) 
closes #1090
=> Adding `tbl_strata(.combine_args=)`

DESCRIPTION, NEWS.md, R/add_p.R, man/add_p.tbl_cross.Rd, man/gtsummary-package.Rd
=> Adding `add_p.tbl_cross(test.args=)` argument

DESCRIPTION, NEWS.md, R/utils-as.R
=> update to missing format printing

DESCRIPTION, NEWS.md, R/add_ci.R
* Fix when using summary type gtsummary selectors (e.g. `all_continuous()`) with the `add_ci(style_fun=)` argument. (#1141)
=>  `add_ci(style_fun=)` argument selector fix

.github/workflows/R-CMD-check-historic-R-versions.yaml, DESCRIPTION, NEWS.md, R/theme_gtsummary.R
* Update to fix encoding issues with the Lancet midpoint on Linux and Mac OS. (#1146)
closes #1146
=> midpoint update

NEWS.md, R/tbl_butcher.R, man/gtsummary-package.Rd, man/tbl_butcher.Rd
* Added `tbl_butcher(include=)` argument allowing users to retain additional elements of the gtsummary object. (#1148)
closes #1148
=> Added `tbl_butcher(include=)` argument

DESCRIPTION, NEWS.md, R/style_number.R, tests/testthat/test-style_number.R
* Updated `style_number()` to no longer use `base::round()` due to its "round-to-even" behavior. All "5" rounding, will now round up. (#1140)
closes #1140
=> Updated `style_number()` to account for the default round-to-even in `base::round()`

.github/pull_request_template.md, R/utils-add_p_tests.R, tests/testthat/test-add_p.tbl_summary.R, tests/testthat/test-modify_cols_merge.R, tests/testthat/test-separate_p_footnotes.R
=> Testing updates

DESCRIPTION, NEWS.md, R/as_gt.R, R/utils-gtsummary_core.R
* Fix in `as_gt()` when there are no hidden columns.
=> Fix in `as_gt()` when there are no hidden columns.

R/add_n.R, man/add_n.tbl_summary.Rd
* updates to the `add_n()` help file
closes #915
=> doc updates to `add_n()`

DESCRIPTION, NEWS.md, pkgdown/_pkgdown.yml, vignettes/gallery.Rmd
The "table gallery" vignette has been updated to be set up as an FAQ section with internal hyperlinks, as well as making some updates to the examples.
closes https://github.com/ddsjoberg/gtsummary/issues/811
=> updating table gallery vignette 

DESCRIPTION, vignettes/tbl_regression.Rmd
=> Testing broom.helpers dev version

DESCRIPTION, NEWS.md, R/as_flex_table.R, R/as_hux_table.R, R/as_kable.R, R/as_kable_extra.R, R/combine_terms.R, R/utils-misc.R, man/as_flex_table.Rd, man/combine_terms.Rd
=> Release Prep

R/as_kable_extra.R, man/as_kable_extra.Rd
Example 3 was removed; updated documentation to Example 2.
=> as_kable_extra() renumber example

DESCRIPTION, NEWS.md, R/set_gtsummary_theme.R, tests/testthat/test-set_gtsummary_theme.R
=> fix in `with_gtsummary_theme()`

R/custom_tidiers.R, man/custom_tidiers.Rd
=> doc update

DESCRIPTION, NEWS.md, R/utils-tbl_summary.R, tests/testthat/test-tbl_summary.R
* Update for `tbl_summary(by=)` that now allows for a column named `"variable"` to be passed. (#1234)
closes #1234
=> Allowing `tbl_summary(by = "variable")` names

DESCRIPTION, NEWS.md, R/inline_text.R, R/tbl_merge.R, tests/testthat/test-inline_text.R, tests/testthat/test-tbl_merge.R
* Adding additional structural checks in `tbl_merge()` and `inline_text()` to provide better error messaging. (#1248)
closes #1248
=> Improved error messaging for non-standard gtsummary object

DESCRIPTION, NEWS.md, R/tbl_custom_summary.R, R/tbl_summary.R, R/tbl_survfit.R, R/tbl_svysummary.R, R/tbl_uvregression.R, R/utils-tbl_summary.R
* The checks for `"haven_labelled"` class are only performed for the in the variables indicated in `include=` and `by=` in `tbl_summary()` and `tbl_svysummary()`. The checks in `tbl_uvregression()` and `tbl_survfit.data.frame()` are only applied to the variables in `include=` (i.e. no including the outcome variables).
closes #1263
=> haven labelled checks

.github/workflows/R-CMD-check.yaml, .github/workflows/pkgdown.yaml, .github/workflows/pr-commands.yaml, .github/workflows/test-coverage.yaml
=> using GH Actions V2

DESCRIPTION, NEWS.md, R/add_global_p.R, R/add_significance_stars.R, R/add_stat.R, R/tbl_merge.R, R/utils-tbl_regression.R, inst/WORDLIST, man/add_significance_stars.Rd, pkgdown/_pkgdown.yml, tests/testthat/test-add_global_p.R
* Updated `add_global_p()` to handle `tbl_uvregression()` objects where users specified the `x=` argument (when `y=` argument is more common). (#1260)
closes #1260
=> add_global_p update for tbl_uvreg(x=)

DESCRIPTION, NEWS.md, R/utils-add_p_tests.R
* Improved error messages for paired tests in `add_p()` and `add_difference()` when `group=` argument is not specified. (#1273)
closes #1273
=> Improved error messages for paired tests in `add_p()` and `add_difference()`

DESCRIPTION, NEWS.md, R/tbl_custom_summary.R, tests/testthat/test-tbl_custom_summary.R
* Fixed bug when a column named "variable" in `tbl_custom_summary(by=)` resulted in an error.
closes #1285
=> Allow column named "variable" in `tbl_custom_summary(by=)`

DESCRIPTION, NEWS.md, R/style_pvalue.R, R/style_ratio.R, R/style_sigfig.R
=> Rounding update

DESCRIPTION, NEWS.md, R/as_tibble.R, tests/testthat/test-as_tibble.R
* Bug fix in `as_tibble(fmt_missing = TRUE)`. Previously, missing assignments applied to more than one row were being ignored. (#1327)
closes #1327
=> Fmt missing fix

.github/workflows/close.yaml
=> Close stale

DESCRIPTION, NEWS.md, R/as_kable_extra.R, tests/testthat/_snaps/as_kable_extra.md, tests/testthat/test-as_kable_extra.R
* [fix latex alignment bug in tbl_stack()](https://github.com/ddsjoberg/gtsummary/commit/ade1ac075da5c1e3659a3245f8230e715f865f02)
* [add snapshot test for latex column alignment with **tbl_stack()](https://github.com/ddsjoberg/gtsummary/commit/77db167f431d38863bc30c16ebab4c3c10841f60)
I'm not sure what the implications are of snapshot tests for package size though, worth considering.
Closes #1326 
=> Kable column alignment

.gitignore, DESCRIPTION, NEWS.md, R/as_gt.R, pkgdown/_pkgdown.yml
* updated indentation implementation for gt tables.
closes #1342
closes #1321
=> indenting update

DESCRIPTION, NEWS.md, R/tbl_survfit.R
=> Added `"var_type"` column to `tbl_survfit()` tbls

.github/workflows/R-CMD-check-historic-R-versions.yaml, DESCRIPTION, vignettes/rmarkdown.Rmd
=> r markdown vignette output type table update

.github/workflows/R-CMD-check-historic-R-versions.yaml, .github/workflows/R-CMD-check.yaml, DESCRIPTION, R/tbl_survfit.R
=> Updated to ubuntu-latest

R/add_ci.R, R/add_n.R, R/as_gt.R, R/modify_table_styling.R, R/tbl_butcher.R, R/utils-add_p_tests.R, R/utils-gtsummary_core.R, R/utils-tbl_summary.R
=> Prepping for purrr v1.0.0 release

DESCRIPTION, NEWS.md, R/custom_tidiers.R, R/plot.R, man/plot.Rd
* Using the ggstats package instead of GGally for plotting regression model coefficients.
closes #1367
closes #1347
=> swapping ggstats

DESCRIPTION, NEWS.md, R/add_overall.R, R/modify.R, R/tbl_custom_summary.R, R/tbl_summary.R, R/tbl_svysummary.R, inst/WORDLIST, tests/testthat/test-modify_caption.R, tests/testthat/test-modify_header.R
* The `modify_cpation()` function now works with tables created with `gtreg::tbl_listing()` that do not contain a column named `"label"`. 
* Functions `tbl_summary()` and `tbl_svysummary()` now support `"{n}"`, `"{p}"`, and `"{level}"` when no `by=` variable is present for use in functions like `modify_header()`. For the survey summary, the unweighted variants are also available.
closes #1366
closes #1358 
=> Updated for overall headers in `modify_header()` and updated to `modify_caption()`

DESCRIPTION, R/tbl_butcher.R, tests/testthat/test-tbl_butcher.R
=> butcher update

DESCRIPTION, NEWS.md, R/custom_tidiers.R, man/custom_tidiers.Rd
* Updated the arguments in `tidy_robust()` to account for updates in {parameters}. (#1376)
closes #1376
=> `tidy_robust()` argument update

.Rbuildignore, DESCRIPTION, NEWS.md, inst/WORDLIST, pkgdown/_pkgdown.yml, vignettes/articles/shiny.Rmd, vignettes/rmarkdown.Rmd
* Added an article illustrating how to utilize gtsummary tables in shiny applications. (#1335)
closes #1335
Hey @parmsam! It's taken time to get a draft together (apologies). Do you want to take a look before I merge it? Any suggested edits? To inspect the results with the Shiny app running properly in the site, you'll need to clone this repo, switch to this PR branch, open in RStudio, and run `pkgdown::build_site()`, then navigate to new article.
=> shiny article

DESCRIPTION, NEWS.md, R/theme_gtsummary.R, tests/testthat/_snaps/set_gtsummary_theme.md, tests/testthat/test-set_gtsummary_theme.R
* Updated Lancet journal theme to report p-values with more precise, per the journal's reporting guidelines. (#1442)
closes #1442
=> Lancet theme update

DESCRIPTION, R/plot.R, man/plot.Rd
=> Issue with `plot.tbl_regression()` example

DESCRIPTION, NEWS.md, R/tbl_uvregression.R, tests/testthat/test-tbl_uvregression.R
* Improved error messaging in `tbl_uvregression()` when `method=` argument is not correctly specified. (#1469)
closes #1469
=> Improved error messaging in `tbl_uvregression(method=)` 

DESCRIPTION, NEWS.md, R/add_overall.R, tests/testthat/_snaps/add_overall.md, tests/testthat/test-add_overall.R
* Bug fix in `add_overall(col_label=)` where specified label was not always placed. (#1505)
closes #1505
=> Bug fix in `add_overall(col_label=)` 

.github/workflows/R-CMD-check-historic-R-versions.yaml, DESCRIPTION, NEWS.md, R/add_p.R, R/deprecated.R
=> removed v1.3.1 deprecation note

DESCRIPTION, NEWS.md, R/utils-add_p.R, tests/testthat/test-add_p.tbl_summary.R
* Bug fix where some default `add_p.tbl_summary()` categorical tests were chi-squared when it should have been Fisher's exact test. This misclassification occurred when there was a large differential in the missing pattern for one of the variables in the cross table. (#1513)
closes #1513 
=> Correction in expected count calculation

DESCRIPTION, NEWS.md, R/remove_row_type.R, R/tbl_stack.R, tests/testthat/_snaps/remove_row_type.md, tests/testthat/_snaps/tbl_stack.md, tests/testthat/test-remove_row_type.R
* Fix in `remove_row_type()` where header rows for `continuous2` type variables was not removed when requested. (#1507)
closes #1507
closes #1512
=>  Fix in `remove_row_type()` 

DESCRIPTION, NEWS.md, R/as_kable.R, man/as_kable.Rd, tests/testthat/_snaps/as_kable.md, tests/testthat/test-as_kable.R
=> remove line breaks in `as_kable()`

DESCRIPTION, NEWS.md, R/add_ci.R, tests/testthat/_snaps/add_ci.md, tests/testthat/test-add_ci.R
* Fix in column order when `add_ci()` is run after `add_overall(last=TRUE)`. Previously, the overall columns were placed in front. (#1525)
closes #1525
=> Overall add ci col order

DESCRIPTION, NEWS.md, R/as_flex_table.R, tests/testthat/_snaps/as_flex_table.md, tests/testthat/test-as_flex_table.R
=> Flextable source note fix

R/add_ci.R, R/add_glance.R, R/tbl_survfit.R, R/utils-tbl_regression.R, R/utils-tbl_summary.R
=> removing some calls to purrr::partial()

R/standalone-forcats.R, R/tbl_summary.R, man/tbl_summary.Rd
=> Updating with the `tbl_summary(sort)` argument

NEWS.md, R/as_gt.R, R/modify_table_styling.R, R/tbl_summary.R, R/utils-as.R, R/utils-gtsummary_core.R, man/dot-table_styling_expr_to_row_number.Rd, man/modify_table_styling.Rd
* Previously, indentation was handled with `modify_table_styling(text_format = c("indent", "indent2"))`, which would indent a cell 4 and 8 spaces, respectively. Handling of indentation has been migrated to `modify_table_styling(indendation = integer())`, and by default, the label column is indented to zero spaces. This makes it easier to indent a group of rows.
* The inputs for `modify_table_styling(undo_text_format)` has been updated to mirror its counterpart `modify_table_styling(text_format)` and no longer accepts `TRUE` or `FALSE`.
=> moving indentation to its own table styling enttry

R/bridge_summary.R, R/select_helpers.R, R/tbl_summary.R, man/dot-list2tb.Rd, tests/testthat/_snaps/tbl_summary.md, tests/testthat/test-tbl_summary.R
=> var_type rename

R/bridge_summary.R, R/card_summary.R, R/tbl_summary.R, man/bridge_summary.Rd, tests/testthat/_snaps/add_p.tbl_summary.new.md, tests/testthat/_snaps/card_summary.md
* Generalizing `brdg_summary()` and supporting `pier_*()` functions
=> Generalizing `brdg_summary()` and supporting `pier_*()` functions

R/as_gt.R, R/modify_table_styling.R, man/modify_column_hide.Rd, man/modify_column_merge.Rd, man/modify_fmt_fun.Rd, man/modify_table_styling.Rd, tests/testthat/_snaps/modify_table_styling.md, tests/testthat/test-modify_table_styling.R
=> v2.0 `modify_table_styling()`

R/modify_table_body.R, man/modify_column_hide.Rd, man/modify_column_merge.Rd, man/modify_fmt_fun.Rd, man/modify_table_body.Rd, man/modify_table_styling.Rd, tests/testthat/_snaps/modify_table_body.md, tests/testthat/test-modify_table_body.R
=> v2.0 `modify_table_body()`

DESCRIPTION, NEWS.md, R/add_stat.R, R/modify.R, R/modify_fmt_fun.R, R/modify_table_styling.R, R/utils-as.R, man/add_stat.Rd, man/modify.Rd, man/modify_column_indent.Rd, man/modify_column_merge.Rd, man/modify_fmt_fun.Rd, man/modify_table_styling.Rd, tests/testthat/test-modify_fmt_fun.R
=> v2.0 `modify_fmt_fun()`

R/import-standalone-check_pkg_installed.R, R/import-standalone-checks.R, R/import-standalone-cli_call_env.R, R/import-standalone-forcats.R, R/import-standalone-stringr.R, R/tbl_summary.R
=> V2.0 standalone updates

R/as_kable.R, R/import-standalone-stringr.R, man/as_kable.Rd, man/as_kable_extra.Rd
=> V2.0 `as_kable()`

tests/testthat/test-add_n.tbl_uvregression.R, tests/testthat/test-add_nevent.tbl_uvregression.R
Added unit tests to `add_n.tbl_uvregression()` and `add_nevent.tbl_uvregression()`
Closes https://github.com/insightsengineering/sme-tasks/issues/685
=> V2.0 add unit tests for `add_n` and `add_nevent` to `tbl_uvregression()` 

DESCRIPTION, R/as_gt.R, R/as_hux_table.R, man/as_hux_table.Rd, man/as_kable_extra.Rd
=> V2.0 `as_hux_table()`

R/card_continuous.R, R/card_summary.R, R/tbl_continuous.R, man/card_continuous.Rd, tests/testthat/_snaps/tbl_continuous.md, tests/testthat/test-tbl_continuous.R
closes https://github.com/insightsengineering/sme-tasks/issues/690
=> V2.0 `tbl_continuous()` testing

R/tbl_ard_summary.R, man/tbl_ard_summary.Rd, tests/testthat/_snaps/tbl_ard_summary.md, tests/testthat/test-tbl_ard_summary.R
=> V2.0 require tbl ard summary by

R/tbl_ard_continuous.R, tests/testthat/_snaps/tbl_ard_continuous.md, tests/testthat/_snaps/tbl_ard_summary.md, tests/testthat/test-tbl_ard_continuous.R, tests/testthat/test-tbl_ard_summary.R
closes https://github.com/insightsengineering/sme-tasks/issues/693
=> V2.0 tests tbl ard continuous

tests/testthat/test-as_flex_table.R
Add v2.0 unit tests for `as_flex_table`.
Part of https://github.com/insightsengineering/sme-tasks/issues/689
Closes https://github.com/insightsengineering/sme-tasks/issues/695
=> v2.0 Add unit tests for  `as_flex_table`

tests/testthat/_snaps/tbl_merge.md, tests/testthat/test-tbl_merge.R
Add v2.0 unit tests for `tbl_merge`.
Part of https://github.com/insightsengineering/sme-tasks/issues/689
Closes https://github.com/insightsengineering/sme-tasks/issues/696
=> v2.0 Add unit tests for `tbl_merge`

R/label_style.R, R/style_number.R, R/style_percent.R, R/style_pvalue.R, R/style_ratio.R, R/style_sigfig.R, man/label_style.Rd, man/style_number.Rd, man/style_percent.Rd, man/style_pvalue.Rd, man/style_ratio.Rd, man/style_sigfig.Rd, man/tbl_strata.Rd, tests/testthat/test-label_style.R, tests/testthat/test-style_sigfig.R
=> V2.0 style unit testing

R/tbl_split.R, man/tbl_split.Rd, tests/testthat/test-tbl_butcher.R, tests/testthat/test-tbl_split.R
=> V2.0 tbl butcher tests

tests/testthat/test-select_helpers.R
=> V2.0 select helpers testing

tests/testthat/_snaps/as_kable.md, tests/testthat/test-as_gt.R, tests/testthat/test-as_kable.R
Add v2.0 unit tests for `as_kable`. Also fixes a few typos in `test-as_gt.R`.
Part of https://github.com/insightsengineering/sme-tasks/issues/689
Closes https://github.com/insightsengineering/sme-tasks/issues/699
=> v2.0 Add unit tests for `as_kable`

DESCRIPTION, R/tbl_summary.R, tests/testthat/_snaps/tbl_summary.md, tests/testthat/test-tbl_summary.R
=> better messaging for continuosu2 summary types

DESCRIPTION, R/as_tibble.R, R/tests.R, R/utils-tbl_regression.R, data-raw/trial.R, man/as_tibble.gtsummary.Rd, tests/testthat/test-add_difference.tbl_summary.R, tests/testthat/test-add_p.tbl_summary.R, tests/testthat/test-add_stat.R, tests/testthat/test-as_gt.R, vignettes/gtsummary_definition.Rmd, vignettes/inline_text.Rmd
=> removing tibble dep

DESCRIPTION, R/assign_summary_digits.R, R/tbl_svysummary.R, R/tbl_uvregression.R, man/tbl_uvregression.Rd, tests/testthat/_snaps/tbl_svysummary.md, tests/testthat/test-tbl_svysummary.R
closes https://github.com/insightsengineering/sme-tasks/issues/707
=> unit testing for `tbl_svysummary()`

DESCRIPTION, R/assign_tests.R, R/tbl_svysummary.R, tests/testthat/_snaps/add_p.tbl_svysummary.md, tests/testthat/_snaps/tbl_svysummary.md, tests/testthat/test-add_p.tbl_svysummary.R
closes https://github.com/insightsengineering/sme-tasks/issues/708
=> Adding `add_p.tbl_svysummary()` unit tests

tests/testthat/_snaps/add_difference.tbl_svysummary.md, tests/testthat/test-add_difference.tbl_svysummary.R
closes https://github.com/insightsengineering/sme-tasks/issues/709
=> adding `add_difference.tbl_svysummary()` unit tests

DESCRIPTION, R/add_ci.R, R/add_ci.tbl_svysummary.R, man/add_ci.tbl_svysummary.Rd, tests/testthat/_snaps/add_ci.tbl_summary.md, tests/testthat/_snaps/add_ci.tbl_svysummary.md, tests/testthat/test-add_ci.tbl_summary.R, tests/testthat/test-add_ci.tbl_svysummary.R
closes https://github.com/insightsengineering/sme-tasks/issues/710
=> UAT for `add_ci.tbl_svysummary()`

NEWS.md, R/add_p.R, R/tbl_custom_summary.R, man/tbl_custom_summary.Rd, tests/testthat/test-tbl_custom_summary.R
restoring feature from previous version of the package, where character statistics would have the default formatting function `as.character()` (thus no need to specify this for users, and this will no longer be a breaking change for v2.0).
FYI @larmarange 
=> `tbl_custom_summary()` default summary update

R/add_q.R, R/add_stat.R, R/modify_column_hide.R, R/tbl_summary.R, man/modify_column_hide.Rd, tests/testthat/_snaps/add_overall.tbl_summary.md, tests/testthat/test-add_overall.tbl_summary.R, tests/testthat/test-add_q.R
=> Addressing some of the TODOs

DESCRIPTION, R/as_gt.R, R/utils-add_p_tests.R, tests/testthat/_snaps/tbl_custom_summary.md
=> updates for emmeans test syntax

R/add_vif.R, tests/testthat/_snaps/add_vif.md, tests/testthat/test-add_vif.R
closes https://github.com/insightsengineering/sme-tasks/issues/713
=> Unit tests for `add_vif()`

R/add_significance_stars.R, tests/testthat/_snaps/add_significance_stars.md, tests/testthat/test-add_significance_stars.R
closes https://github.com/insightsengineering/sme-tasks/issues/714
=> Unit tests for `add_significant_stars()`

R/add_glance.R, man/add_glance.Rd, man/add_vif.Rd, tests/testthat/test-add_glance.R
closes https://github.com/insightsengineering/sme-tasks/issues/715
=> `add_glance()` UAT

tests/testthat/_snaps/add_overall.tbl_continuous.md, tests/testthat/test-add_overall.tbl_continuous.R
closes https://github.com/insightsengineering/sme-tasks/issues/716
=> UAT for `add_overall.tbl_continuous()`

tests/testthat/_snaps/add_n.tbl_svysummary.md, tests/testthat/test-add_n.tbl_svysummary.R
closes https://github.com/insightsengineering/sme-tasks/issues/717
=> UAT `add_n.tbl_svysummary()`

tests/testthat/_snaps/add_stat_label.tbl_svysummary.md, tests/testthat/test-add_stat_label.tbl_svysummary.R
closes https://github.com/ddsjoberg/gtsummary/pull/1824
=> UAT for `add_stat_label.tbl_svysummary()`

R/tbl_summary.R, R/theme_gtsummary.R, man/theme_gtsummary.Rd, tests/testthat/_snaps/theme_gtsummary.md, tests/testthat/test-theme_gtsummary.R
=> Adding some theme tests

tests/testthat/_snaps/custom_tidiers.md, tests/testthat/test-custom_tidiers.R
=> Adding tests for custom tidiers

tests/testthat/_snaps/add_overall.tbl_svysummary.md, tests/testthat/test-add_overall.tbl_svysummary.R, tests/testthat/test-add_stat.R, tests/testthat/test-separate_p_footnotes.R
closes https://github.com/insightsengineering/sme-tasks/issues/718
=> UAT for `add_overall.tbl_svysummary()`

NEWS.md, R/theme_gtsummary.R, tests/testthat/_snaps/theme_gtsummary.md, tests/testthat/test-theme_gtsummary.R
=> journal theme UAT

R/combine_terms.R, man/combine_terms.Rd, tests/testthat/_snaps/combine_terms.md, tests/testthat/test-combine_terms.R
Add v2.0 unit tests for `combine_terms`. Also fixes a labelling bug in the function.
Part of https://github.com/insightsengineering/sme-tasks/issues/689
Closes https://github.com/insightsengineering/sme-tasks/issues/712
=> v2.0 Add unit tests for `combine_terms`

tests/testthat/test-modify_caption.R, tests/testthat/test-modify_footnote.R, tests/testthat/test-modify_header.R, tests/testthat/test-modify_spanning_header.R
added unit tests for Dynamic values in header, spanning header, footnote, and caption
=> added unit tests for Dynamic values

tests/testthat/test-inline_text.R
=> Skip some snapshot unit tests for older dplyr

R/assign_summary_digits.R, R/select_helpers.R, man/scoping_gtsummary.Rd
=> More scoping updates

R/tbl_custom_summary.R, R/tbl_svysummary.R, R/utils-tbl_custom_summary.R, man/proportion_summary.Rd, man/ratio_summary.Rd, man/tbl_custom_summary.Rd, man/tbl_svysummary.Rd, man/tests.Rd
=> few improvements in tbl_custom_summary() documentation

tests/testthat/test-tbl_strata.R
Increase test coverage for `tbl_strata` by adding a test for survey objects.
Follow up to https://github.com/insightsengineering/sme-tasks/issues/719
=> v2.0 Add test for `tbl_strata` with survey objects

DESCRIPTION
Update min R version to 4.2
closes #1870
=> Update DESCRIPTION R min version

DESCRIPTION, R/tbl_ard_continuous.R, R/tbl_ard_summary.R, R/tbl_ard_wide_summary.R
=> Improved `tbl_ard_*(card)` error messaging

DESCRIPTION, tests/testthat/_snaps/tbl_uvregression.md
=> Bump min version required for {broom.helpers}

DESCRIPTION, R/tbl_ard_continuous.R, R/tbl_ard_summary.R
improving error messaging for malformed ARD inputs
closes #1977
=> improving error messaging for malformed ARD inputs

tests/testthat/_snaps/custom_tidiers.md, tests/testthat/test-custom_tidiers.R
=> updating snapshot to ignore deprecation msg out of our control

R/tbl_summary.R, tests/testthat/test-tbl_summary.R
=> retain label for data frames

DESCRIPTION, tests/testthat/test-add_ci.tbl_svysummary.R
=> Check ordering in svy CIs

R/add_p.R, R/add_p.tbl_continuous.R, man/add_p.tbl_continuous.Rd, tests/testthat/test-add_p.tbl_continuous.R
=> Updated examples in `add_p.tbl_continuous()`

DESCRIPTION, R/custom_tidiers.R, R/deprecated.R, R/deprecated_ci_column.R, R/inline_text.tbl_cross.R, R/inline_text.tbl_survfit.R, R/modify_table_styling.R, R/plot.R, R/separate_p_footnotes.R, R/tbl_custom_summary.R, R/tbl_split.R, R/tbl_strata.R, R/utils-tbl_custom_summary.R, man/continuous_summary.Rd, man/custom_tidiers.Rd, man/deprecated.Rd, man/deprecated_ci_column.Rd, man/inline_text.tbl_cross.Rd, man/inline_text.tbl_survfit.Rd, man/modify_table_styling.Rd, man/plot.Rd, man/proportion_summary.Rd, man/ratio_summary.Rd, man/separate_p_footnotes.Rd, man/tbl_custom_summary.Rd, man/tbl_split.Rd, man/tbl_strata.Rd
=> Remove `RdMacros: lifecycle`

pkgdown/_pkgdown.yml, vignettes/articles/tbl_ard-functions.Rmd, vignettes/articles/tbl_regression.Rmd, vignettes/articles/tbl_summary.Rmd
=> Minor article updates

R/tbl_strata_nested_stack.R, man/tbl_strata_nested_stack.Rd, tests/testthat/_snaps/tbl_strata_nested_stack.md, tests/testthat/test-tbl_strata_nested_stack.R
=> `tbl_indent_id` column rename

R/tbl_summary.R, tests/testthat/_snaps/tbl_summary.md, tests/testthat/_snaps/tbl_svysummary.md
=> Adding a missing error env to abort call

R/add_glance.R, tests/testthat/test-add_n.tbl_regression.R, tests/testthat/test-add_nevent.tbl_regression.R, tests/testthat/test-as_flex_table.R, tests/testthat/test-as_gt.R, tests/testthat/test-as_kable.R, tests/testthat/test-as_kable_extra.R, tests/testthat/test-as_tibble.R, tests/testthat/test-combine_terms.R, tests/testthat/test-inline_text.R, tests/testthat/test-modify_column_alignment.R, tests/testthat/test-modify_column_hide.R, tests/testthat/test-modify_footnote.R, tests/testthat/test-modify_header.R, tests/testthat/test-modify_missing_symbol.R, tests/testthat/test-modify_table_body.R, tests/testthat/test-modify_table_styling.R, tests/testthat/test-select_helpers.R, tests/testthat/test-tbl_butcher.R, tests/testthat/test-tbl_merge.R, tests/testthat/test-tbl_regression.R, tests/testthat/test-tbl_stack.R, tests/testthat/test-theme_elements_gtsummary.R, tests/testthat/test-theme_gtsummary.R
=> skipping tests/examples when suggests pkgs not installed

DESCRIPTION, tests/testthat/test-tbl_summary.R
=> Col order fix for lgl variables

DESCRIPTION, R/tbl_survfit.R, vignettes/articles/tbl_ard-functions.Rmd
=> Updates for `tbl_survfit()` after cardx update

DESCRIPTION, NEWS.md, R/add_overall.R, R/as_tibble.R, inst/WORDLIST, tests/testthat/test-add_overall.tbl_summary.R
=> Fix for styling in add_overall()

R/import-standalone-forcats.R
closes #2226 
Introduce this check: https://github.com/insightsengineering/standalone/pull/16
=> update forcats standalone script

R/tests.R, inst/WORDLIST, man/tbl_split_by.Rd, man/tbl_svysummary.Rd, tests/testthat/_snaps/tbl_hierarchical.md, tests/testthat/test-tbl_hierarchical.R
* Updated expected warnings in `tbl_hierarchical()` tests after `ard_stack_hierarchical()` update.
Also tidied up other files causing notes.
=> Update `tbl_hierarchical()` test warnings after `ard_stack_hierarchical()` update

R/tbl_split.R, man/tbl_split_by.Rd
* Fixed output 3rd examples from `tbl_split_by_rows()`.
#2273
=> Fix example in `tbl_split`
