ddsjoberg/gtsummary

R/inline_text.R, R/style_sigfig.R, R/tbl_survival.R, man/style_sigfig.Rd, man/tbl_survival.survfit.Rd, tests/testthat/test-inline_text.R, tests/testthat/test-tbl_survival.R
This PR includes major re-write to `tbl_survival()`, which leads to downstream consequences for `inline_text()`.
1. The structure is more general, such that updates to report the results in a wide format are more easily incorporated.  The output object includes two versions of the results: `table_body`  and `table_long`.  The first will always be used by `print.tbl_survival()` and `as_gt()`.  `table_long` is a static table that has all the results included.  This table will be used to reference cells to extract in the `inline_text()` function (which will stay the same regardless of any wide formatting that has been applied). #70 
1. Previously, the confidence interval was created and formatted in the {gt} function `cols_merge()`.  The CI is now a formatted string column in the results …
=> #61 survival quantiles

DESCRIPTION, NEWS.md, R/tbl_regression.R, R/tbl_uvregression.R, codemeta.json, man/add_p.Rd, man/add_p_.Rd, man/tbl_regression.Rd, man/tbl_uvregression.Rd, tests/testthat/test-tbl_uvregression.R
What changes are proposed in this pull request?
- added include and exclude arguments to tbl_ubregression()
If there is an GitHub issue associated with this pull request, please provide link.
- #240 
\* If this is PR into the master branch, use [this checklist](https://raw.githubusercontent.com/ddsjoberg/gtsummary/master/.github/pull_request_into_master_checklist.md).
=> 240 tbl uvregression update

DESCRIPTION, R/tbl_regression.R, R/tbl_uvregression.R, man/tbl_regression.Rd, man/tbl_uvregression.Rd
Added a note about the deprecated argument `show_noyes=` in `tbl_regression()` and `tbl_uvregression()`
=> added show_noyes deprecation note

DESCRIPTION, NEWS.md, R/tbl_merge.R, codemeta.json, inst/WORDLIST, man/tbl_merge.Rd
`tbl_merge()` now interprets `tab_spanner = ` with `gt::md()`
Need to double check this does NOT cause problems if gt is not installed on a machine....
#253 
=> bolding spanning headers #253

.travis.yml, DESCRIPTION, codemeta.json
Now only deploying pkgdown website via Travis when on release version
=> Travis update

DESCRIPTION, NEWS.md, R/tbl_summary.R, codemeta.json, tests/testthat/test-tbl_summary.R
In `tbl_summary()` execution in halted with an error if the by variable has any missing values.  This PR now continues execution and prints a message about missing variables being omitted.
#279 
=> 279 missing by

DESCRIPTION, NEWS.md, R/as_gt.R, codemeta.json
Small update that looks for the option `gtsummary.as_gt.addl_cmds` which can contain {gt} calls that will be appended to the end of the `.$gt_calls` list when printing.
Users must be careful, however....these must be commands that can be called on any gtsummary table.
=> Option to append any gt call to the end of a gtsummary print

DESCRIPTION, NEWS.md, R/tbl_regression.R, R/tbl_stack.R, R/tbl_uvregression.R, codemeta.json, inst/WORDLIST, man/add_n.Rd, man/add_overall.Rd, man/add_p.Rd, man/add_q.tbl_summary.Rd, man/add_stat_label.Rd, man/bold_italicize_labels_levels.Rd, man/bold_p.tbl_summary.Rd, man/inline_text.tbl_summary.Rd, man/modify_header.Rd, man/sort_p.tbl_summary.Rd, man/tbl_merge.Rd, man/tbl_stack.Rd, man/tbl_summary.Rd, man/tbl_uvregression.Rd, pkgdown/_pkgdown.yml, tests/testthat/test-tbl_stack.R, tests/testthat/test-tbl_uvregression.R, vignettes/gallery.Rmd, vignettes/global_options.Rmd, vignettes/tbl_regression.Rmd, vignettes/tbl_summary.Rmd
- no longer installing gt from github
- added gt to a drat repo, and installing from there 
- added functionality for `tbl_uvregression()` to keep a co variate constant and vary the outcome. (#294)
- fixed bug where labels for `tbl_uvregression()` and `tbl_regression()` could not be passed as named lists.
- changed the label header in `tbl_uvregression()` and `tbl_regression()` from **Characteristic** to **Covariate**.  In `tbl_uvregression()`, if the user specified the `x=` argument (rather than `y=), the header is now **Outcome**
=> 294 uvregress x

DESCRIPTION, NEWS.md, R/utils-add_p.R, codemeta.json
- **What changes are proposed in this pull request?** - Previously p-value calculations that threw a warning were not included in summary tables. With this PR, the warning is displayed, but the p-value calculation is still completed and p-value is available in tables. 
- **If there is a GitHub issue associated with this pull request, please provide link.**
#283 
Code to test warnings:
```
library(tidyverse)
df <- tribble( ~x, ~y, ~z,
0, 2, 0,
3, 4, 0,
3, 4, 1,
1, 0, 0 )
df %>%
tbl_summary(by = y) %>%
add_p(test = all_numeric() ~ "chisq.test")
```
Code to test errors + warnings:
```
library(tidyverse)
df <- tribble( ~x, ~y, ~z, 
0, 0, 0,
0, 0, 0,
0, 4, 1,
0, 0, 0 )
df %>%
tbl_summary(by = y) %>%
add_p(test = all_numeric() ~ "chisq.test")
``` …
=> # 283 update add_p() warnings and errors

R/bold_italicise_labels_levels.R, R/tbl_merge.R, R/tbl_regression.R, R/tbl_summary.R, R/tbl_uvregression.R, R/utils-table_headers.R
The gt package has deprecated `cells_data()` in favor of `cells_body()`
=> updated cells_data to cells_body

.github/pull_request_template.md, DESCRIPTION, NEWS.md, R/as_gt.R, R/tbl_regression.R, R/tbl_summary.R, R/utils-tbl_summary.R, codemeta.json, tests/testthat/test-tbl_summary.R, tests/testthat/test-tbl_summary_input_checks.R
Functions `all_categorical()`, `all_dichotomous()`, and `all_continuous()` may now be used in `tbl_summary()` argument `type=`.  We now make our best guess for the type each column is (i.e. continuous, categorical, or dichotomous).  After we make a guess, the user may use  `all_dichotomous()` to change all columns defaulting to dichotomous to categorical, for example (`type = all_dichotomous() ~ "categorical"`).
We also will now throw an error is the user requests a factor or character to be summarized continuously.
There were all small updates the the PR template and error messaging in `tbl_regression()`.
#256, #320 …
=> 256 gtsummary select functions in type argument

DESCRIPTION, NEWS.md, R/utils-tbl_regression.R, codemeta.json, tests/testthat.R
`tryCatch()` statements now surround the calls to the `tidy()` functions.  If the tidier produces an error, the user is alerted of the problem (rather than making it look like a gtsummary problem)
#338, #337
=> Try catch for tidiers

.travis.yml, DESCRIPTION, NEWS.md, R/add_nevent.R, R/tbl_regression.R, R/utils-tbl_regression.R, codemeta.json, man/add_nevent.tbl_regression.Rd
- The minimum R version is reduced to 3.3, with Travis CI updated to check.
- broom.mixed was removed, as broom had all tidiers needed
#356, #354
=> 356 min r version

inst/WORDLIST, vignettes/gtsummary_definition.Rmd
This PR adds vignette outlining the basics of a gtsummary object.  The vignette is meant to serve a reference for anyone looking to add to the gtsummary package (and to help the authors remember the ins and outs!).  
This vignette will be built with the package, but will not be added the pkgdown site.
#355
=> 355 gts definition

DESCRIPTION, NEWS.md, R/tidyselect_to_list.R, codemeta.json, tests/testthat/test-tbl_summary.R
Bug fix when a data frame with one column was passed to `tbl_summary()`
#389 
=> 389 data subset bug

DESCRIPTION, R/combine_terms.R, codemeta.json, tests/testthat/test-combine_terms.R
This PR adds a check to ensure `anova()` returns a p-value.
#401 
=> added check for missing p-values in combine terms

DESCRIPTION, NEWS.md, R/add_overall.R, R/bold_italicise_labels_levels.R, R/tbl_merge.R, R/tbl_stack.R, codemeta.json, tests/testthat/test-combine_terms.R
Removes class checking for each type gtsummary type, and made `tbl_stack()`, `tbl_merge()`, `bold_labels()` (and friends) generic and now just checks for class gtsummary.
Now works with `tbl_ancova()`
```r
tbl_ancova_ex1 <-
trial %>%
bstfun::tbl_ancova(y = c("age", "marker"), x = "trt")
tbl_ancova_ex2 <-
trial %>%
bstfun::tbl_ancova(y = c("age", "marker"), x = "trt")
tbl_stack(list(tbl_ancova_ex1, tbl_ancova_ex2))
tbl_merge(list(tbl_ancova_ex1, tbl_ancova_ex2))
```
#373 
=> #373 checking for gtsummary class, rather than individual tbl type

NEWS.md, R/tbl_summary.R, tests/testthat/test-tbl_summary.R
In `tbl_summary()` passing an ordered factor in the `by=` argument no longer causes as error.
Reported by @ahinton-mmc
=> bug fix for ordered factors

DESCRIPTION, NEWS.md, R/utils-tbl_regression.R, codemeta.json, tests/testthat/test-tbl_regression.R
Previously, it was not possible to change the interaction label. It was always `"Variable 1 Label * Variable 2 Label"`. But now, the interaction label can be updated.
Moreover, the `show_single_row=` argument ignored interaction terms, and now that is remedied.
Need to check the update works for multiple model types, and does not break any existing labeling/showing on a single row.
closes #451 
closes #452 
```r
lm(age ~ factor(response) * marker, trial) %>%
tbl_regression(
show_single_row = `factor(response):marker`,
label = list(
`factor(response)` ~ "Tumor Response",
`factor(response):marker` ~ "Interaction"
)
)
``` …
=> tbl_regression interaction updates

DESCRIPTION, NEWS.md, R/add_p.R, R/utils-add_p.R, R/utils-gtsummary_core.R, tests/testthat/test-add_p.R
We've always had issues when users utilized custom p-value functions in `add_p.tbl_summary()`. After looking into it, it seems the problem was some careless programming that led to ambiguous environment searching for the user's custom function.
I've gone through the function and made the environments explicit, and I think it's solved the problem.  I've also made the following updates
- Users can pass their custom p-value function as a quoted string or bare.
- The basic functions for calculating pvalues, such as `t.test()` can now be passed directly.  We now perform a check match check for functions passed. If it is passed, we replace it with our version that returns the p-value and assigns the test name, e.g. `test = age ~ t.test`
- If a …
=> add_p fixes

R/add_nevent.R, R/as_flextable.R, R/as_kable.R, R/as_kable_extra.R, R/tbl_regression.R, R/tbl_uvregression.R
@moleps noted formatting issues with some columns using `as_flextable()`.  This PR addresses the formatting problems.
1. flextable handles missing values for numeric and character columns differently. Numeric missing prints `NA`, and character `""`. In gtsummary that were printed as numeric columns because the default looked good (all columns were integers).  Added a formatting function to those columns to force conversion to character.
1. Spanning headers were being printed in alphabetical order! Update to preserve the ordering.
#482 
=> fixes for flextable output

DESCRIPTION, NEWS.md, R/add_overall.R, R/add_p.R, R/add_stat_label.R, R/tbl_summary.R, R/utils-add_p.R, R/utils-tbl_summary.R, man/add_p.tbl_cross.Rd, man/tbl_summary.Rd, tests/testthat/test-add_p.R, tests/testthat/test-inline_text.R, tests/testthat/test-select_helpers.R, tests/testthat/test-tbl_regression.R, tests/testthat/test-tbl_summary_input_checks.R
The `include=` argument has been added to `tbl_summary()`. This largely affects `add_p()`, where users no longer need to include a `group=` variable in the summary table before `add_p()`.  This is the new preferred syntax:
```r
tbl_summary(trial, include = -response) %>% 
add_p(group = response)
```
The response column will not be included in the summary table, but is available as a grouping variable in `add_p()`
closes #477 
=> added include arg to tbl_summary

DESCRIPTION, NEWS.md, R/as_tibble.R
All columns in `as_tibble()` are now styled and converted to character. Previoulsy, styling was applied to most columns, but there were a few that relied on default printing for the type of underlying data.  This was ok to rely on this default behavior for `as_kable()`, but with the introduction of `as_flextable()` we needed to style and format each column to character. Potential to break some code in edge cases. (#493)  
closes #493 
=> Coerce cols to character in as_tibble()

DESCRIPTION, NEWS.md, R/as_flextable.R, man/as_flextable.Rd
Made some updates to the way flextables are printed when there are spanning headers.
#499 
=> updating as felxtable when spanning header present

DESCRIPTION, NEWS.md, R/utils-tbl_summary.R, tests/testthat/test-tbl_summary.R
Added an error message when bad stats are requested in `tbl_summary(statistic=)`. For example, requesting a mean for a categorical variable. 
closes #502 
``` r
trial %>%
dplyr::select(grade, trt) %>%
tbl_summary(statistic = everything() ~ "{mean}")
#> Error: Problem with `mutate()` input `tbl_stats`.
#> x There was an error assembling the summary statistics for 'grade'
#>   with summary type categorical.
#> 
#> There are 2 common sources for this error.
#> 1. You have requested summary statistics meant for continuous
#>    variables for a variable being as summarized as categorical.
#>    To change the summary type to continuous …
```
=> Update error messaging when bad args are passed to tbl_summary(statistic=)

DESCRIPTION, NEWS.md, R/utils-tbl_regression.R, R/vetted_models.R, man/vetted_models.Rd, tests/testthat/test-inline_text.R
When there is a level of a variable that is an empty string, we are seeing an error when the variable is then printed using `inline_text.tbl_summary()`.
```r
trial %>%
select(grade) %>%
mutate(grade = ifelse(grade == "I", "", as.character(grade))) %>%
tbl_summary() %>%
inline_text(variable = grade, level = "II")
```
Also, updated the vetted models example to not use `tidy_confint()` as it is now deprecated.
related to #508 (but does not close that issue)
closes #505
=> empty string bug fix for selectors

R/theme_gtsummary.R, man/theme_gtsummary.Rd, vignettes/themes.Rmd
Minor typo and wording changes to the new theme_gtsummary documentation and theme vignette. 
=> typo fixes to theme doc + vignette

DESCRIPTION, NEWS.md, R/style_ratio.R, codemeta.json, tests/testthat/test-style_ratio.R
Prior to update, `style_ratio()` didn't accurately round values near one.
``` r
c(0.99, 1.1) %>%
style_ratio()
#> [1] "1.0"  "1.10"
```
After the bug fix, it's all good.
``` r
c(0.99, 0.999,  1.1) %>%
style_ratio()
#> [1] "0.99" "1.00" "1.10"
```
closes #651
=> `style_ratio()` rounding bug near one #651

DESCRIPTION, NEWS.md, R/tbl_uvregression.R, inst/WORDLIST, tests/testthat/test-add_glance_source_note.R, tests/testthat/test-tbl_uvregression.R
The arguments `estimate_fun` and `pvalue_fun` were being ignored in `tbl_uvregression()` due to a bug where they were not being passed to `tbl_uvregression()`
=> Bug fix where fmt_funs from tbl_uvregression were being ignored

DESCRIPTION, NEWS.md, R/utils-tbl_summary.R, tests/testthat/test-set_gtsummary_theme.R
Bug fix when a default statistic is set using themes for `"continuous2"` variables that has length larger than one
First reported here: https://stackoverflow.com/questions/64528291/set-theme-for-categorical-and-continuous-variables-in-gtsummary-package-for-tbl
=> Continuous2 theme bug

DESCRIPTION, NEWS.md, R/tbl_svysummary.R, R/tbl_uvregression.R, inst/WORDLIST, man/tbl_svysummary.Rd, man/tbl_uvregression.Rd, tests/testthat/test-tbl_uvregression.R
* `tbl_uvregression()` now accepts both data frames and survey objects as input.
closes #742
```r
tt <- survey::svydesign(~1, data = as.data.frame(Titanic), weights = ~Freq) 
tbl <- 
tt %>%
tbl_uvregression(
y = Survived,
method = survey::svyglm,
method.args = list(family = binomial),
hide_n = TRUE
)
tbl
```
=> `tbl_uvregression()` to accept survey objects

DESCRIPTION, NEWS.md, R/as_gt.R
Fix for bug report on spanning header with gt output
https://stackoverflow.com/questions/65882941/r-gtsummary-overall-column-moved-after-merge
=> added spanning header to column that are cleaned

DESCRIPTION, NEWS.md, R/as_kable_extra.R
* Bug fix for spanning headers with kableExtra output. The spanning header was misplaced when the header text was sandwhiched between two blank spanning headers.
=> Kable extra spanning bug

DESCRIPTION, NEWS.md, R/utils-add_p.R, tests/testthat/test-add_difference.R, tests/testthat/test-add_p.tbl_summary.R
When a column is all NA, a test is now assigned. Previously no test was assigned and resulted in an error
closes #889
=> Fix for #889

DESCRIPTION, NEWS.md, R/as_kable_extra.R, man/as_kable_extra.Rd, renv.lock, tests/testthat/test-as_kable_extra.R
- Bold and italic requests are now ignored for kableExtra output. These are carried out via markdown syntax, which is not supported by {kableExtra} (#917)
closes #917
=> Bold and italic requests are now ignored for kableExtra output

DESCRIPTION, NEWS.md, R/as_flex_table.R, R/as_hux_table.R, man/as_flex_table.Rd, man/as_hux_table.Rd, man/as_kable_extra.Rd, renv.lock
* huxtable previously stripped markdown old syntax from column headers and spanning headers. The output now uses markdown syntax in the headers by default using `huxtable::set_markdown()` (#885)
closes #885
=> Use markdown by default in huxtable header rows

R/tbl_merge.R, tests/testthat/test-tbl_merge.R
* Fix in `tbl_merge()` when no rows in a table are present in the first table. (#1033)
closes #1033
=> Column ordering fix in `tbl_merge()`

DESCRIPTION, NEWS.md, R/utils-tbl_summary.R, tests/testthat/test-tbl_svysummary.R
* Added `style_percent()` as the default formatting function for unweighted proportions. (#1181)
closes #1181 
=> Added default formatting function for unweighted proportions

DESCRIPTION, NEWS.md, R/add_difference.R, R/add_glance.R, R/add_q.R, R/add_significance_stars.R, R/add_stat.R, R/add_stat_label.R, R/add_vif.R, R/as_flex_table.R, R/as_gt.R, R/as_hux_table.R, R/as_kable.R, R/as_kable_extra.R, R/bold_italicise_labels_levels.R, R/bold_p.R, R/combine_terms.R, R/modify.R, R/modify_cols_merge.R, R/modify_column_alignment.R, R/modify_column_hide.R, R/modify_fmt_fun.R, R/modify_table_body.R, R/modify_table_styling.R, R/remove_row_type.R, R/separate_p_footnotes.R, R/sort_filter_p.R, R/utils-misc.R, tests/testthat/test-as_gt.R
* Improved error messaging the functions `as_gt()`, `as_kable()`, `as_flex_table()`, `as_hux_table()` when an object that is not class 'gtsummary' is passed. (#1188)
closes #1188
=> Improving error messaging in `as_gt()`

DESCRIPTION, NEWS.md, R/bold_italicise_labels_levels.R
* Functions `bold_labels()`, `bold_levels()`, `italicize_labels()`, and `italicize_levels()` now bold/italicize the first column shown in the table. Previously, the `"label"` column (which is most often the first shown column) was styled.
=> bolding first column (not always label column)

DESCRIPTION, NEWS.md, R/utils-tbl_custom_summary.R, R/utils-tbl_summary.R, man/add_glance.Rd, man/add_p.tbl_survfit.Rd, man/add_stat_label.Rd, man/gtsummary-package.Rd, man/proportion_summary.Rd, man/syntax.Rd, man/tbl_survfit_errors.Rd, man/tests.Rd
* Updates to labels and default formatting functions of unweighted statistics presented in `tbl_svysummary()`. (#1253)
closes #1253
=> Fmt fun unweighted

DESCRIPTION, NEWS.md, R/set_gtsummary_theme.R, R/tbl_survfit.R, man/set_gtsummary_theme.Rd, tests/testthat/test-set_gtsummary_theme.R
* Added argument `with_gtsummary_theme(msg_ignored_elements=)` argument. Use this argument to message users if any theme elements will be overwritten and therefore ignored inside the `with_gtsummary_theme()` call.
closes #1266
closes #1265
``` r
list("tbl_summary-str:continuous_stat" = "{median}") %>%
set_gtsummary_theme()
with_gtsummary_theme(
x = list("tbl_summary-str:continuous_stat" = "{mean}"),
expr = tbl_summary(trial, include = age) %>% as_kable(),
msg_ignored_elements = "Theme element(s) {.val {elements}} is/are utilized internally and were ignored."
)
#> ℹ Theme element(s) "tbl_summary-str:continuous_stat" is/are utilized …
```
=> added new messaging arg to with theme fn

tests/testthat/test-plot.R
Running tests on Conda Forge [failed due to lack of `ggstats`](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=624425&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642&l=538) in testing environment. This PR suggests the `test-plot.R` test(s) be conditioned on `ggstats` availability.
=> Ensure ggstats when testing

DESCRIPTION, R/add_ci.R, R/inline_text.R, R/tbl_regression.R, R/utils-misc.R
Hi there, we were running revdeps for dplyr 1.1.0 and this package was indirectly flagged through a breakage in {logitr}, which relies on this package.
``` r
library(logitr)
model <- logitr(
data    = yogurt,
outcome = "choice",
obsID   = "obsID",
pars    = c("price", "feat", "brand")
)
#> Running model...
#> Done!
model |> 
tbl_regression()
#> Error in `dplyr::rename_with()` at dplyr/R/join.R:321:2:
#> ! `.fn` must return a vector of length 0, not 1.
#> Backtrace:
#>     ▆
#>  1. ├─gtsummary::tbl_regression(model)
#>  2. ├─gtsummary:::tbl_regression.default(model) at gtsummary/R/tbl_regression.R:108:2
#>  3. │ └─... %>% ... at gtsummary/R/tbl_regression.R:250:2
#>  4. ├─dplyr::relocate(., starts_with("modify_stat_"), .after = last_col())
#>  5. ├─dplyr::full_join(., …
```
=> Use `vec_paste0()` helper for better recycling

DESCRIPTION, NEWS.md, R/as_flex_table.R, tests/testthat/test-as_flex_table.R
* Fix for `as_flex_table()` when the header is blank. (#1406)
closes #1406
=> fix when column has a blank header

R/tbl_strata.R, man/tbl_strata.Rd
Quiet argument no longer passed to `tbl_stack()`
closes #1755
=> Closes #1755 `tbl_strata(.quiet)` fix

R/add_difference.R, R/add_difference.tbl_svysummary.R, R/modify.R, man/add_difference.tbl_summary.Rd, man/add_difference.tbl_svysummary.Rd, tests/testthat/test-modify_header.R, tests/testthat/test-show_header_names.R
We've deprecated the `modify_*(update)` argument. This was previously the first argument and has been moved to the end. So previously, `modify_header(list(label = "Variable"))` was the same as `modify_header( update = list(label = "Variable"))`.
But now that argument is position matched to the dots (`...`), and `list(label = "Variable")` is not how the the dots want the argument passed. The dots want to see `modify_header(label = "Variable")`.
We are updating the deprecation notice to check the value of the first position matched argument to ensure it follows the updated structure.
Thank you @ayogasekaram for flagging! …
=> Updating deprecation message for `modify_*()` functions

R/add_significance_stars.R, R/tbl_survfit.R, tests/testthat/test-tbl_survfit.R
* When checking that the class of a value is numeric, also allow integers.
Closes #1867 
=> Allow integers in numeric class checks

NEWS.md, R/brdg_summary.R, tests/testthat/test-tbl_summary.R
* Correct the order of the columns when the `tbl_summary(by)` variables has ten or more levels. (#1877)
closes #1877
=> Correct order when the `tbl_summary(by)` variable has 10+ levels

NEWS.md, R/inline_text.tbl_summary.R, tests/testthat/test-inline_text.R
* Restore functionality of `inline_text.tbl_summary(column)` argument to specify a by level when the by variable is a factor: a regression introduced in v2.0.0. (#1883)
closes #1883
=> Restore functionality in `inline_text.tbl_summary(column)`

DESCRIPTION, NEWS.md, R/brdg_summary.R, R/tbl_summary.R, tests/testthat/_snaps/tbl_ard_summary.md, tests/testthat/_snaps/tbl_summary.md, tests/testthat/_snaps/tbl_svysummary.md
* Re-establishing strong link between header by variable levels and those in the table body to ensure correct ordering of columns in `tbl_summary()`.
=> Adding strong connection between `tbl_summary(by)` order and order in table_body

DESCRIPTION, NEWS.md, R/tbl_uvregression.R, tests/testthat/test-tbl_uvregression.R
* Fix in `tbl_uvregression()` for the `formula` argument when it includes a hard-coded column name, e.g. `formula='{y} ~ {x} + grade'`. The hard-coded variable name is now removed from the `include` argument. This was a regression introduced in the v2.0.0 release. (#1886)
closes #1886
=>  Fix in `tbl_uvregression()` for the `formula` argument

DESCRIPTION, NEWS.md, R/assign_summary_digits.R, tests/testthat/test-tbl_summary.R
* Updated the styling function from `style_percent()` to `style_number(scale=100)` when user passes an integer to change the rounding of percentages in `tbl_summary()`. (#1899)
closes #1899
=> Update styling function for p statistic when integer passed

NEWS.md, R/tbl_ard_summary.R, man/tbl_ard_summary.Rd
* Updated the default value of `tbl_ard_summary(missing)` to `"no"`
closes #1857 
=> updated default value of `tbl_ard_summary(missing)` to `"no"`

DESCRIPTION, NEWS.md, R/add_glance.R, tests/testthat/test-add_glance.R
* The default `add_glance_*(glance_fun)` function fixed for `mice` models with class `'mira'`. (#1912)
closes #1912 
=> fix for add_glance*() for MICE models and the default  glance fun

DESCRIPTION, R/tbl_uvregression.R, tests/testthat/_snaps/tbl_summary.md, tests/testthat/test-tbl_summary.R, tests/testthat/test-tbl_uvregression.R
The fix was in the cards pkg, where there was an issue with `cli::cli_format()` incorrectly formatting factor variables. We now coerce them to character before printing conditions.
closes #1915 
=> Fix in printing error/warning conditions

R/select_helpers.R, man/select_helpers.Rd, man/tests.Rd
Adding `sdif` into the list of contrasts in `all_contrats()`
=> since version 1.14.0, `broom.helpers` support `MASS::contr.sdif()`

DESCRIPTION, NEWS.md, R/add_stat_label.R, R/brdg_continuous.R, R/brdg_summary.R, R/tbl_ard_continuous.R, R/tbl_ard_summary.R, R/tbl_continuous.R, R/tbl_custom_summary.R, R/tbl_summary.R, R/tbl_svysummary.R, R/utils-cards.R, tests/testthat/_snaps/tbl_ard_continuous.md, tests/testthat/_snaps/tbl_ard_summary.md, tests/testthat/test-modify_header.R, tests/testthat/test-tbl_ard_summary.R
* We can again report unweighted statistics in the headers of `tbl_svysummary()` tables. (#1911)
* The total N is now returned with `.$cards` using the `cards::ard_total_n()` function for the calculation.
* The default headers for `tbl_ard_*()` functions no longer include counts, as these are not required data to be passed along in the ARD input.
closes #1911
=> Unweighted stats in `tbl_svysummary()` headers fix

DESCRIPTION, NEWS.md, R/brdg_summary.R, R/tbl_ard_continuous.R, tests/testthat/_snaps/tbl_ard_continuous.md, tests/testthat/_snaps/tbl_ard_summary.md, tests/testthat/test-tbl_ard_continuous.R, tests/testthat/test-tbl_ard_summary.R
* The summary statistics of the `'by'` variable are no longer required in the ARD for functions `tbl_ard_summary()` and `tbl_ard_continuous()`. When the tabulation summary statistics are passed, they are available to place in the header dynamically. (#1860)
closes #1860
=> No longer require `by` variable summary stats in `tbl_ard_summary(by)` and `tbl_ard_continuous(by)`

R/add_ci.R, R/add_ci.tbl_svysummary.R, man/tbl_ard_continuous.Rd, tests/testthat/test-add_ci.tbl_summary.R, tests/testthat/test-add_ci.tbl_svysummary.R
Adding messaging when `tbl_summary(percent='column')` is not used.
closes #1927
=> adding additional `add_ci()` messaging

DESCRIPTION, NEWS.md, R/tbl_ard_continuous.R, R/tbl_ard_summary.R, R/tbl_ard_wide_summary.R, man/tbl_ard_continuous.Rd, man/tbl_ard_summary.Rd, man/tbl_ard_wide_summary.Rd, tests/testthat/test-tbl_ard_continuous.R, tests/testthat/test-tbl_ard_summary.R, tests/testthat/test-tbl_ard_wide_summary.R
* Added the `label` argument to functions `tbl_ard_summary()`, `tbl_ard_wide_summary()`, and `tbl_ard_continuous()`. (#1850)
closes #1850
=> Added the `label` argument to functions `tbl_ard_summary()`, `tbl_ard_wide_summary()`, and `tbl_ard_continuous()`

DESCRIPTION, NEWS.md, R/tbl_uvregression.R, tests/testthat/_snaps/tbl_uvregression.md, tests/testthat/test-tbl_uvregression.R
* `tbl_uvregression()` properly handles variables specified in the `include` argument with non-syntactic names. (#1932)
closes #1932
=> syntactic names fix in `tbl_uvregression(include)`

DESCRIPTION, NEWS.md, R/add_stat_label.R, tests/testthat/_snaps/add_stat_label.md, tests/testthat/test-add_stat_label.R
* `NA` values can again be specified in `add_stat_label(label)` to suppress a statistic label from being placed. (#1937)
closes #1937
=> `add_stat_label(label)` allows NA values 

DESCRIPTION, NEWS.md, R/tbl_cross.R, tests/testthat/_snaps/tbl_cross.md, tests/testthat/test-tbl_cross.R
* Corrected bug in `tbl_cross()` where the `digits` argument was not always being passed accurately to `tbl_summary()`. (#1943)
closes #1943
=> Corrected bug in `tbl_cross(digits)`

DESCRIPTION, NEWS.md, R/add_p.R, R/add_stat.R, R/add_vif.R, R/combine_terms.R, R/tbl_uvregression.R, tests/testthat/_snaps/add_overall.tbl_ard_summary.md, tests/testthat/_snaps/add_stat.md, tests/testthat/test-add_stat.R
* Fix where error or warning condition messages containing curly brace pairs could not be printed.
=> Curly brace pairs condition printing fix

DESCRIPTION, NEWS.md, R/modify.R, man/modify.Rd, tests/testthat/_snaps/show_header_names.md, tests/testthat/test-show_header_names.R
* Updated the `show_header_names()` output to include the values that may be dynamically placed in the headers. Additionally, the `include_example` and `quiet` arguments have been deprecated. (#1696)
Related #1696
=> Updated `show_header_names()` output format

DESCRIPTION, NEWS.md, R/as_gt.R, R/print.R
* Headers in {gt} tables being exported to PDF do not support the `\n` line breaker. Previously, line breakers were stripped from the header in the `print.gtsummary()` S3 method. But this did not apply to users utilizing `as_gt()` to further customize their tables. As a result, the line breaking strip has been migrated to `as_gt()`. (#1960)
closes #1960 
=> Migrating gt->PDF line breaking code to `as_gt()`

DESCRIPTION, NEWS.md, R/add_overall_ard.R, man/add_overall_ard.Rd
* Removed documentation for the `add_overall.tbl_ard_summary(digits)` argument, which was never meant to be a part of this function. (#1975)
closes #1975
=> Removed `add_overall.tbl_ard_summary(digits)` argument

DESCRIPTION, R/tbl_continuous.R, R/tbl_summary.R, tests/testthat/test-tbl_ard_continuous.R, tests/testthat/test-tbl_ard_summary.R, tests/testthat/test-tbl_ard_wide_summary.R
Ensuring `tbl_ard_*()` function can ingest ARDs from their `tbl_*()` counterparts
closes #1991 
=> Ensuring `tbl_ard_*()` function can ingest ARDs from their `tbl_*()` counterparts

NEWS.md, R/tbl_survfit.R, man/tbl_survfit.Rd, tests/testthat/test-tbl_survfit.R
* Migrated the `tbl_survfit.list(conf.level)` up to `tbl_survfit.data.frame(conf.level)` where the confidence level is passed to `survival::survfit()`.
=> Migrate `tbl_survfit(conf.level)` argument to data frame method

R/brdg_hierarchical.R, R/brdg_summary.R, R/tbl_ard_hierarchical.R, R/tbl_hierarchical.R, R/tbl_summary.R
* Created separate internal processing function `.add_gts_column_to_cards_hierarchical()` from `.add_gts_column_to_cards_summary()` and removed `hierarchical` argument from internal function `.add_table_styling_stats()`.
Closes #2033 
=> Separate internal hierarchy processing from summary functions

NEWS.md, R/tbl_summary.R, tests/testthat/test-tbl_summary.R
* Addressing encoding issue where `sort()` and `dplyr::arrange()` sorted differently, and the order of the `by` levels was inconsistent in the resulting table. (#2038)
closes #2038 
=> `tbl_summary(by)` order of levels in table with encoding issue

R/add_global_p.R, man/add_global_p.Rd, tests/testthat/test-add_global_p.R, tests/testthat/test-add_global_p.tbl_regression.R, tests/testthat/test-add_global_p.tbl_uvregression.R, tests/testthat/test-add_p.tbl_summary.R, tests/testthat/test-add_stat.R, tests/testthat/test-combine_terms.R, tests/testthat/test-separate_p_footnotes.R, tests/testthat/test-tbl_regression_methods.R, tests/testthat/test-theme_gtsummary.R
* Adds missing packages to `skip_if_not(is_pkg_installed(...))` calls in tests to prevent errors from occurring when tests are run without all suggested packages installed.
=> Add missing `skip_if_not(is_pkg_installed(...))` calls to tests

DESCRIPTION, NEWS.md, R/set_gtsummary_theme.R, tests/testthat/_snaps/theme_gtsummary.md, tests/testthat/test-theme_gtsummary.R
* The `with_gtsummary_theme()` has been updated to no longer print theme names when the applied, nor when the original theme is re-applied. (#2031)
closes #2031
=> No longer printing theme names in `with_gtsummary_theme()`

DESCRIPTION, NEWS.md, R/modify_caption.R, man/modify_caption.Rd, man/tests.Rd, tests/testthat/test-modify_caption.R
* The `modify_caption(caption)` argument now accepts a vector of captions, instead of just a string. Note, however, that not all print engines support a vector of captions. (#2107)
closes #2107
=> The `modify_caption(caption)` argument now accepts a vector

DESCRIPTION, NEWS.md, R/utils-gtsummary_core.R, gtsummary.Rproj, man/tests.Rd, tests/testthat/test-tbl_merge.R
* Swapped out `dplyr::rows_update()` with a base R implementation in `tbl_merge()` that allows for tables with mixed types in `x$table_styling$header$modify_*` columns. For example, `tbl_summary()` has integer Ns and `tbl_svysummary()` has double Ns that can now be combined. (#1626)
closes #1626
=> Swapping in base R rows update instead of `dplyr::rows_update()`

DESCRIPTION, NEWS.md, R/add_ci.R, tests/testthat/test-add_ci.tbl_summary.R
* The `add_ci.tbl_summary()` function now works with categorical variables that were summarized using `tbl_summary(percent = c('row', 'cell'))`. (#1929)
closes #1929
=> Allowing `tbl_summary(percent=c('row','cell'))` in `add_ci()`

DESCRIPTION, vignettes/articles/gallery.Rmd
As discussed in the issue, here's an example of using robust standard errors. I had to add a dependency (under suggests) for sandwich. I hope thats OK. If you happen to know of an existing dependency that contains a function for modifying the vcov matrix, i'm happy to try that instead.
<< Addition of an example on robust standard errors to the gallery vignette >>
closes #2076 
=> add robust errors to gallery

DESCRIPTION, NEWS.md, R/utils-misc.R, tests/testthat/test-tbl_summary.R
* The `tbl_summary(statistic)` argument now allows users to pass curly brackets that appear in the final table. Just like in `glue::glue()` double curly brackets are escaped to a single bracket. For example, `tbl_summary(statistic=~"{{{mean}}}")` results in `"{<mean value>}"`. (#2123)
closes #2123
=> Allowing rendered curly brackets in `tbl_summary(statistic)` 

DESCRIPTION, NEWS.md, R/add_ci.R, tests/testthat/test-add_ci.tbl_summary.R
* When `add_ci.tbl_summary()` was for a variable that was all `NA` we no longer return an error. Users will now see the confidence interval as `'NA%, NA%'`. (#2139)
closes #2139
=> `add_ci()` on all `NA` columns

DESCRIPTION, NEWS.md, R/modify.R, R/modify_abbreviation.R, R/modify_bold_italic.R, R/modify_column_merge.R, R/modify_footnote.R, R/modify_source_note.R, man/add_glance.Rd, man/modify.Rd, man/modify_abbreviation.Rd, man/modify_bold_italic.Rd, man/modify_column_merge.Rd, man/modify_footnote2.Rd, man/modify_source_note.Rd, tests/testthat/_snaps/modify_bold_italic.md, tests/testthat/test-modify_abbreviation.R, tests/testthat/test-modify_bold_italic.R, tests/testthat/test-modify_column_merge.R, tests/testthat/test-modify_footnote_body.R, tests/testthat/test-modify_footnote_header.R, tests/testthat/test-modify_source_note.R, vignettes/gtsummary_definition.Rmd
* The `remove_*()` family of functions default argument values have been updated to remove _all_ footnotes, source notes, abbreviations, column merging, bold and italic styling by default, so the users are not longer required to remove, for example, one source note at a time. The one except is `remove_spanning_headers()`, which will remove the first level spanning headers be default. (#2161)
closes #2161
=> Updating `remove_*()` function defaults

DESCRIPTION, NEWS.md, R/tbl_strata_nested_stack.R, man/add_glance.Rd, man/tbl_strata_nested_stack.Rd, tests/testthat/test-tbl_strata_nested_stack.R
* The `tbl_strata_nested_stack(quiet)` argument documentation was updated. (#2164)
* Corrected the class of objects returned from `tbl_strata_nested_stack()`.
* Corrected bug in `tbl_strata_nested_stack()` when the strata variable had a single level. Pervasively, the indentation of the single strata level was not correct.
closes #2164
=> updates for `tbl_strata_nested_stack()` 

DESCRIPTION, NEWS.md, R/tbl_cross.R, tests/testthat/test-tbl_cross.R
* Fixed bug in `tbl_cross()` when a column was named `'missing'`. (#2182)
closes #2182
=> bug in `tbl_cross()` when a column was named `'missing'`

DESCRIPTION, NEWS.md, R/add_significance_stars.R, tests/testthat/test-add_significance_stars.R
* The footnote placed on the p-value column by `add_significance_stars()` no longer replaces any existing footnote. Rather the footnote is added to any existing footnote. (#2184)
closes #2184 
=> No longer replace existing footnote with the stars footnote

DESCRIPTION, NEWS.md, R/add_variable_group_header.R, tests/testthat/_snaps/add_variable_group_header.md, tests/testthat/test-add_variable_group_header.R
* The `add_variable_group_header()` function has been generalized to work with gtsummary tables, where previously only `'tbl_summary'` were accepted. (#2197)
closes #2197
=> Generalizing `add_variable_group_header()`

DESCRIPTION, NEWS.md, R/brdg_hierarchical.R, tests/testthat/_snaps/tbl_hierarchical.md, tests/testthat/test-tbl_hierarchical.R
* Fixed a bug in `tbl_hierarchical()` where the `group*` variables of the resulting `table_body` were not fully populated.
Closes #2192 
=> Populate all `group*` variables in `table_body` when no `by` variable present

DESCRIPTION, NEWS.md, R/gather_ard.R, R/tbl_regression.R, R/tbl_uvregression.R, tests/testthat/test-gather_ard.R
* Fix in `gather_ard()` for `tbl_regression()` and `tbl_uvregression()`. Previously, only the ARD for the primary regression model(s) would be returned, and now all ARDs are returned including those from subsequent calls to `add_*()` functions. (#2208)
closes #2208
=> Fix in `gather_ard()` for regression tables

DESCRIPTION, NEWS.md, R/tbl_merge.R, tests/testthat/_snaps/tbl_merge.md, tests/testthat/test-tbl_merge.R
* Fix in `tbl_merge(merge_vars)` argument when a table contained a `"row_type"` column and the tables were not merged by this variable (which is included in the default). (#2205)
closes #2205
=> Fix in `tbl_merge(merge_vars)` argument

DESCRIPTION, NEWS.md, R/brdg_summary.R, tests/testthat/test-as_hux_table.R, tests/testthat/test-tbl_svysummary.R
* Fix in `tbl_svysummary(missing='ifany')` when the weighted number of missing observations was <= 0.5. Previously, these counts were coerced to integer and rounded to zero, and therefore, did not appear in the table. (#2229)
closes #2229
=> Fix for missing counts < 0.5 in tbl_svysummary()

DESCRIPTION, NEWS.md, R/add_overall.R, R/brdg_hierarchical.R, tests/testthat/_snaps/add_overall.tbl_continuous.md, tests/testthat/_snaps/add_overall.tbl_summary.md, tests/testthat/_snaps/add_overall.tbl_svysummary.md, tests/testthat/_snaps/tbl_hierarchical.md, tests/testthat/test-add_overall.tbl_continuous.R, tests/testthat/test-add_overall.tbl_summary.R, tests/testthat/test-add_overall.tbl_svysummary.R
* The `add_overall()` function no longer returns an error when an unstratified table is passed. Rather, a message is printed and the unaltered table is returned.
=> No longer err for unstratified table passed to `add_overall()`

DESCRIPTION, NEWS.md, R/filter_hierarchical.R, R/sort_hierarchical.R, tests/testthat/test-filter_hierarchical.R
* Fixed bug in `filter_hierarchical()` causing an error for unstratified tables.
Closes #2233 
=> Fix `filter_hierarchical()` bug when no `by` variable present

DESCRIPTION, NEWS.md, R/sort_hierarchical.R, R/tbl_hierarchical.R, man/tbl_ard_hierarchical.Rd, man/tbl_hierarchical.Rd, tests/testthat/test-sort_hierarchical.R
* Fixed bug in `sort_hierarchical()` causing some rows to be dropped when sorting unstratified tables.
Closes #2237 
=> Fix bug in `sort_hierarchical()` when no `by` variable is present

DESCRIPTION, NEWS.md, R/brdg_hierarchical.R, R/filter_hierarchical.R, R/sort_hierarchical.R, R/tbl_ard_hierarchical.R, R/tbl_hierarchical.R, R/tbl_split.R, man/filter_hierarchical.Rd, man/sort_hierarchical.Rd, man/tbl_ard_hierarchical.Rd, man/tbl_hierarchical.Rd, man/tbl_split_by.Rd, tests/testthat/_snaps/sort_hierarchical.md, tests/testthat/test-add_overall.tbl_hierarchical.R, tests/testthat/test-filter_hierarchical.R, tests/testthat/test-show_header_names.R, tests/testthat/test-sort_hierarchical.R, tests/testthat/test-tbl_ard_hierarchical.R, tests/testthat/test-tbl_ard_summary.R, tests/testthat/test-tbl_hierarchical.R, vignettes/articles/tbl_ard-functions.Rmd
- Refactored `sort_hierarchical()` to allow for different sorting methods at each hierarchy variable level.
- Updated `sort_hierarchical()` and `filter_hierarchical()` to always keep attribute and total N rows at the bottom of the ARD.
- Removed sorting code from the main hierarchical table functions - default sorting now occurs during the ARD creation step. This prevents sorted ARDs from losing their sorted order when using `tbl_ard_hierarchical()`.
- Removed `TRTA` derivation when using the `cards::ADSL` dataset in examples/tests.
Closes #2280 
Blocked by https://github.com/insightsengineering/cards/pull/493 - update Remotes field after merging cards PR …
=> Make hierarchical table sorting more flexible

DESCRIPTION, NEWS.md, R/tbl_stack.R, tests/testthat/_snaps/tbl_stack.md, tests/testthat/test-tbl_stack.R
* Greatly improved messaging when column headers differ in `tbl_stack()`. (#2266)
close #2266
=> Improve messaging in `tbl_stack()`

DESCRIPTION, NEWS.md, R/tbl_summary.R, man/tbl_summary.Rd, tests/testthat/_snaps/tbl_summary.md, tests/testthat/test-tbl_summary.R
* When a data frame is passed in the `tbl_summary(percent)` argument, the headers are now tabulated with this data frame. (#2322)
closes #2322
=> Using `tbl_summary(percent=<data.frame>)` for header counts
